--QUESTÃO 1

SELECT 
    D.DEP_NOME AS 'DEPARTAMENTO',
    P.PRO_DES_PRODUTO AS 'DESCRIÇÃO DO PRODUTO',
    P.PRO_PRECO AS 'VALOR DA VENDA',
    D.DEP_DESCONTO AS 'DESCONTO'
FROM TB_DEPARTAMENTOS D
JOIN TB_PRODUTOS P ON D.DEP_CODIGO = P.PRO_DEP_CODIGO
WHERE P.PRO_QT_ESTOQUE > P.PRO_QT_MINIMA
ORDER BY    D.DEP_NOME ASC
GO


--QUESTÃO 2

SELECT 
    D.DEP_NOME AS 'DEPARTAMENTO',
    P.PRO_DES_PRODUTO AS 'DESCRIÇÃO DO PRODUTO',
    P.PRO_PRECO AS 'VALOR DA VENDA',
    D.DEP_DESCONTO AS 'DESCONTO'
FROM TB_DEPARTAMENTOS D
JOIN TB_PRODUTOS P ON D.DEP_CODIGO = P.PRO_DEP_CODIGO
WHERE D.DEP_NOME = 'CALÇADOS'
GO

--QUESTÃO 3
--Nome e telefone de todos os clientes dos bairros TIROL, ALECRIM, ou RIBEIRA, por 
--ordem de nome do cliente.
CREATE TABLE TB_TEL_CLIENTES(
    TEC_TELEFONE VARCHAR(11) NOT NULL,
    TEC_CLI_CODIGO INTEGER
    CONSTRAINT FK_CLI_TEC FOREIGN KEY(TEC_CLI_CODIGO)
        REFERENCES TB_CLIENTES(CLI_CODIGO)
)   

INSERT INTO TB_TEL_CLIENTES (TEC_TELEFONE, TEC_CLI_CODIGO)
VALUES 
    ('84123456789',1),('11235468798',2),('84123554689',3),('21125458725',4),('31255447785',5)
GO


SELECT* FROM TB_TEL_CLIENTES

SELECT
    C.CLI_NOME AS 'NOME DO CLIENTE',
    TC.TEC_TELEFONE AS 'TELEFONE DO CLIENTE'
FROM TB_CLIENTES C
JOIN TB_BAIRROS B ON B.BAI_CODIGO = C.CLI_BAI_CODIGO
JOIN TB_TEL_CLIENTES TC ON C.CLI_CODIGO = TC.TEC_CLI_CODIGO
WHERE B.BAI_NOME LIKE 'PONTA VERDE' OR B.BAI_NOME LIKE 'BARRA DO CEARÁ'
ORDER BY C.CLI_NOME ASC
GO

--QUESTÃO 4
--Nome e telefone de todos os fornecedores das cidades NATAL ou PARNAMIRIM, 
--por ordem de nome do fornecedor.4

SELECT * FROM TB_BAIRROS B
GO
CREATE TABLE TB_FORNECEDORES(
    FOR_CODIGO INTEGER IDENTITY NOT NULL,
    FOR_BAI_CODIGO INTEGER NOT NULL,
    FOR_NOME VARCHAR(50) NOT NULL,
    FOR_CNPJ VARCHAR(15) NOT NULL,
    FOR_WEBSITE VARCHAR(20),
    FOR_DES_MUNICIPAL VARCHAR(20),
    FOR_DES_ESTADUAL VARCHAR(20),
    FOR_LOGRADOURO VARCHAR(50),
    FOR_NUMERO VARCHAR(6),
    FOR_CEP VARCHAR(10),
    CONSTRAINT PK_FORNECEDORES PRIMARY KEY(FOR_CODIGO),
    CONSTRAINT FK_BAI_FOR FOREIGN KEY(FOR_BAI_CODIGO)
        REFERENCES TB_BAIRROS(BAI_CODIGO)
)
GO

CREATE TABLE TB_TEL_FORNECEDORES(
    TEF_TELEFONE VARCHAR(11) NOT NULL,
    TEF_FOR_CODIGO INTEGER,
    CONSTRAINT FK_FOR_TEF FOREIGN KEY(TEF_FOR_CODIGO)
        REFERENCES TB_FORNECEDORES(FOR_CODIGO)
)
GO

INSERT INTO TB_FORNECEDORES (FOR_BAI_CODIGO, FOR_NOME, FOR_CNPJ, FOR_WEBSITE, FOR_DES_MUNICIPAL, FOR_DES_ESTADUAL, FOR_LOGRADOURO, FOR_NUMERO, FOR_CEP)
VALUES
(1, 'Empresa A', '12345678901234', 'www.empresaA.com', 'NATAL', 'Estadual A', 'Rua A', '123', '12345-678'),
(2, 'Empresa B', '56789012345678', 'www.empresaB.com', 'PARNAMIRIM', 'Estadual B', 'Rua B', '456', '56789-012'),
(3, 'Empresa C', '90123456789012', 'www.empresaC.com', 'JOÃO PESSOA', 'Estadual C', 'Rua C', '789', '90123-456'),
(4, 'Empresa D', '23456789012345', 'www.empresaD.com', 'NATAL', 'Estadual D', 'Avenida X', '789', '23456-789'),
(5, 'Empresa E', '89012345678901', 'www.empresaE.com', 'MACAU', 'Estadual E', 'Rua Y', '101', '89012-345'),
(6, 'Empresa F', '34567890123456', 'www.empresaF.com', 'PARNAMIRIM', 'Estadual F', 'Avenida Z', '222', '34567-890')
GO

INSERT INTO TB_TEL_FORNECEDORES(TEF_TELEFONE, TEF_FOR_CODIGO)
VALUES
    ('8425452568',1),('8425452555',2),('55258741258',3),('11255443568',4),('84221133665',5),('31125542587',6)
GO

SELECT 
    F.FOR_NOME AS 'FORNECEDORES',
    TEF.TEF_TELEFONE AS 'TELEFONE DOS FORNECEDORES'
FROM TB_FORNECEDORES F
JOIN TB_TEL_FORNECEDORES TEF ON TEF.TEF_FOR_CODIGO = F.FOR_CODIGO
WHERE F.FOR_DES_MUNICIPAL BETWEEN 'NATAL' AND 'PARNAMIRIM'
ORDER BY F.FOR_NOME ASC

GO


